StudyingProject/project/urls.py
from django.contrib import admin
from django.urls import path
from myproject import views

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.myhome, name='home'),
    path('design/', views.design, name='design'),
    path('contacts/', views.contacts, name='contacts'),
]

StudyingProject/myproject/models.py
from django.db import models

# Create your models here.
class Customer(models.Model):
    
    email = models.CharField(max_length=256, blank=False)
    name = models.CharField(max_length=50, blank=False)
    interior = models.BooleanField(default=False)
    logo = models.BooleanField(default=False)
    graphic = models.BooleanField(default=False)

StudyingProject/myproject/forms.py
from django import forms
from django.forms import fields
from .models import Customer


class CustomersForm(forms.ModelForm):
    
    class Meta:
        model = Customer
        fields = ['email', 'name', 'interior', 'logo', 'graphic']

StudyingProject/myproject/views.py
from django.shortcuts import render
from .forms import  CustomersForm
from django.core.mail import EmailMultiAlternatives
from django.http import JsonResponse

def attached(interior, logo, graphic):
    htmlcontent = ''
    if interior == 'true' and logo == 'true' and graphic == 'true':
        with open('myproject\static\\attachments\emailattach.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent
    elif interior == 'false' and logo == 'false' and graphic == 'false':
        return htmlcontent
    elif interior == 'true' and graphic == 'true':
        with open('myproject\static\\attachments\\attachGraphicInterior.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent
    elif graphic == 'true' and logo == 'true':
        with open('myproject\static\\attachments\\attachGraphicLogo.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent
    elif interior == 'true' and logo == 'true':
        with open('myproject\static\\attachments\\attachLogoInterior.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent
    elif interior == 'true':
        with open('myproject\static\\attachments\\attachInterior.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent
    elif logo == 'true':
        with open('myproject\static\\attachments\\attachLogo.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent
    elif graphic == 'true':
        with open('myproject\static\\attachments\\attachGraphic.html', 'r') as file:
            htmlcontent = file.read()
        return htmlcontent

def contacts(request):

    if request.method == "POST":
        email = request.POST['email']
        name = request.POST['name']
        interior = request.POST['interior']
        logo = request.POST['logo']
        graphic = request.POST['graphic']

        htmlcontent = attached(interior, logo, graphic)
        message = EmailMultiAlternatives(
            'Examples of works',
            f'From Sokol Design Company.Good day {name}.',
            'buble.1205@gmail.com',
            [f'{email}'],
            reply_to=['buble.1205@gmail.com'],
        )

        if htmlcontent != '':
            form = CustomersForm(request.POST)
            if form.is_valid(): form.save()
            message.attach_alternative(htmlcontent, 'text/html')
            message.send(fail_silently=False)
            return JsonResponse({'result': name,})
        else:
            return JsonResponse({'result': 'error'}, status=500)
    else:
        return render(request, 'myproject\contacts.html')

def myhome(request):
    return render(request, 'myproject\home.html')

def design(request):
    return render(request, 'myproject\designs.html')

StudyingProject/myproject/templates/myproject/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shorctut icon" href="{% static 'image/color_palette_brush_paint_icon_193916.ico' %}" type="image/x-icon">
    <title>Sokol Design</title>
    {% block title %}
    {% endblock %}
</head>
<body>
    {% block content %}
    {% endblock %}
    <div id="footer" class="container-fluid">
        <div class="row row-col-2">
          <div class="col-sm-6"><p>This site is an intellectual property of Sokol Design</p></div>
          <div class="col"><p>My social media <a href="https://instagram.com/_sokolenok_1?utm_medium=copy_link"><img id="instagram" src="{% static 'image/instagram.svg' %}"></a></p></div>
        </div>
      </div>
</body>
</html>

StudyingProject/myproject/templates/myproject/contacts.html
{% extends 'myproject/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style_contacts.css' %}">
    {% endblock %}
</head>
<body>
    {% block content %}
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/contacts.js' %}"></script>

    <a name="top"></a>
    <div id="curtain" style="display: none;position:absolute;width:100vw;height:1900px;background-color:black;opacity: 0.4; z-index: 1;"></div>
    <div class="container-fluid">
        <div style="text-align: center;" class="row row-cols-3">
            <div class="col"><a href="{% url 'home'%}"><p>HOME</p></a></div>
            <div class="col"><a href="{% url 'design' %}"><p>DESIGNS</p></a></div>
            <div class="col"><a href="#top"><p>CONTACTS</p></a></div>
        </div>
    </div>
    <div class="d-flex justify-content-center">
        <div class="spinner-border" style="display:none;position:absolute;color:#4da8a8;margin-top:calc(100vh - 35%);z-index:2;width:5rem;height:5rem;" role="status">
          <span class="sr-only">Loading...</span>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div id="FormSquare" style="font-family: Robot, sans-serif; font-weight: 700;">
                <p>Sokol Design is a team of designers who love their work and treat each new project with responsibility and diligence.<br> We believe that the environment in which human beings live should be not only functional, but also aimed at positive emotion.<br>

                    Every new decision is your fantasies and desires, realized by us.<br><p>
                </div>
            </div>
        </div>
    </div>
        <div style="padding-bottom: 20%;" class="container">
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    <div>
                        <form id="FormSquare" action="" method="post" name="customer"> {% csrf_token %}
                            <div class="row">
                                <p>If you need some new albums about Design.<br>
                                Please fill your information in the form below.<br></p>
                            </div>
                            <div class="row">
                                <label><b>Your email:<br></b></label>
                                <input  id="id_email" style="width: 100%;" type="text" name="email" placeholder="Email"></input>
                            </div>
                            <div class="row">
                                <div style="display: none" id="errorEmail"><h3><b>Please input correct email.</h3></b></div>
                            </div>
                            <br>
                            <div class="row">
                                <label><b>Your name:<br></b></label>
                                <input id="id_name" style="width: 100%;" type="text" name="name" placeholder="Name"></input>
                            </div>
                            <div class="row">
                                <div style="display: none" id="errorName"><h3><b>Please input correct name.</h3></b></div>
                            </div>
                            <br>
                            <div class="row">
                                <p><b>Choose some attachments that you need:</b></p>
                            </div>
                            <div class="row">
                                <input style="margin: .4rem;" id="id_graphic" type="checkbox" name="graphic" value="true"></input>
                                <label for="graphic"><b>Graphic</b></label>
                            </div>
                            <div class="row">
                                <input style="margin: .4rem;" id="id_interior" type="checkbox" name="interior" value="true"></input>
                                <label for="interior"><b>Interior</b></label>
                            </div>
                            <div class="row">
                                <input style="margin: .4rem;" id="id_logo" type="checkbox" name="logo" value="true"></input>
                                <label for="logo"><b>Logo</b></label>
                            </div>

                            <br><br>
                            <div class="row">
                                <button type="button" class="btn btn-primary" id="send">Send</button>
                            </div>
                            
                            <button style="display: none;" id="modalWindow" type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop"></button>
                              <div  class="modal fade" id="staticBackdrop" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                  <div style="background-color: off-white !important;" class="modal-content">
                                    <div style="border-bottom: 1px solid #333333 !important;"class="modal-header">
                                      <h5 class="modal-title" id="staticBackdropLabel">Thank you!</h5>
                                      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="false">&times;</span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                      <p id="good" style="display: none;"><span id="customer"></span> we sent you an email.<br></p>
                                      <p id="bad" style="display: none;">Please choose your attachments!</p>
                                    </div>
                                    <div style="border-top: 1px solid #333333 !important;" class="modal-footer">
                                      <button type="button" class="btn btn-primary" data-dismiss="modal">Ok</button>
                                    </div>
                                  </div>
                                </div>
                              </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endblock %}
</body>
</html>

StudyingProject/myproject/templates/myproject/designs.html
{% extends 'myproject/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style_design.css'%}">
    {% endblock %}
</head>
<body>
    {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
      <div class="container-fluid">
        <div style="text-align: center;" class="row row-cols-3">
          <div class="col"><a href="{% url 'home' %}"><p>HOME</p></a></div>
          <div class="col"><a href="#top"><p>DESIGNS</p></a></div>
          <div class="col"><a href="{% url 'contacts'%}"><p>CONTACTS</p></a></div>
        </div>
      </div>
      <div class="container">
        <p id="textHeader">INTERIOR</p>
        <div class="row">
          <div id="carousel_1" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image/design/Entrance/Entrance_1.svg' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image/design/Entrance/Entrance_2.svg' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_1" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_1" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <div id="carousel_2" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image/design/Entrance/Entrance_4.svg' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image/design/Entrance/Entrance_6.svg' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_2" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_2" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        <div class="row">
          <div id="carousel_3" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image/design/Studio/Studio_1.svg' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image/design/Studio/Studio_3.svg' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_3" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_3" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <div id="carousel_4" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image/design/Entrance/Entrance_3.svg' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image/design/Entrance/Entrance_5.svg' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_4" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_4" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>

        </div>
      </div>
      <div id="entranceText" class="container">
        Interior design is an important component of the quality of human life.<br>
          I believe that the environment in which it is located should be not only functional, but also directed to positive emotional charge.<br>
          Every new decision is your fantasy and desire that I realize.
      </div>
      <div class="container">
        <p id="textEntrance">Graphic</p>
        <div class="row">
          <div id="carousel_5" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image/design/Graphic/Graphic_1.png' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image/design/Graphic/Graphic_3.png' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_5" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_5" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <div id="carousel_6" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image/design/Graphic/Graphic_4.png' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image/design/Graphic/Graphic_1.png' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_6" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_6" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        </div>
      </div>
      <div id="entranceText" class="container">
        I have a great deal of experience in working with a material nature.<br>
          I took a professional course in academic painting, academic drawing, composition, coloristics and coloring, photography and video graphics, and many other things to become a specialist in the field of design.<br>
           So far, I've been perfecting my drawing and painting skills.<br> I'm trying to apply these learned abilities to every educational design project.
      </div>
      <div class="container">
        <p id="textEntrance">Logo</p>
        <div class="row">
          <div id="carousel_7" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image\design\Logo\logo_2.svg' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image\design\Logo\logo_2.svg' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_7" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_7" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
          <div id="carousel_8" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="5000">
                <img src="{% static 'image\design\Logo\logo_2.svg' %}" class="d-block w-100" >
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="{% static 'image\design\Logo\logo_2.svg' %}" class="d-block w-100" >
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carousel_8" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carousel_8" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
        </div>
      </div>
      <div id="entranceText" class="container">
        What's the perfect logo?<br>
          The perfect logo is the one that combines both the latest trends of design in the world and your personal, special desires.<br><br>
          Sooner or later, each of us wonders whether we need a logo for a personal blog, a small business, or a big firm. My job is to help design a design that fits the customer's needs for different functions.
      </div>
      {% endblock %}
</body>
</html>

StudyingProject/myproject/templates/myproject/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="shorctut icon" href="{% static 'image/color_palette_brush_paint_icon_193916.ico' %}" type="image/x-icon">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style_home.css' %}">
  <title>Sokol Design</title>
</head>
<body>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  <div id="wrapper">
  <a name="top"></a>
  <div id="frame" class="container">
    <div id="header">
      <div style="margin: 0%;" class="row">
        <img id="logo" src="{%static 'image/home/HeaderLogo.svg' %}">
      </div>
    </div>
    <div id="plug"></div>
    <div id="navbar" class="container">
      <div class="row row-cols-3">
        <div class="col"><a href="#top"><p>HOME</p></a></div>
        <div class="col"><a href="{% url 'design' %}"><p>DESIGNS</p></a></div>
        <div class="col"><a href="{% url 'contacts' %}"><p>CONTACTS</p></a></div>
      </div>
    </div>
    <div id="carousel_1" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="5000">
          <img src="{% static 'image/home/Carousel1_1.svg'%}" class="d-block w-100" alt="image">
        </div>
        <div class="carousel-item" data-bs-interval="5000">
          <img src="{% static 'image/home/Carousel1_2.svg'%}" class="d-block w-100" alt="image">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carousel_1" data-bs-slide="prev">
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carousel_1" data-bs-slide="next">
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    <div id="text" class="container">
      <div class="row">
        <p>We visualize the space for a cozy and comfortable life.<br> But whatever the task is, above all, it is important for us to maintain a pleasant communication and understanding between designer and customer.
          <br><br>
          We want to hear your requests and desires, make the design individual and special, because the quality of the project depends on these important factors.</p>
          <br><br><br>
          <p>Sokol Design is a team of designers who love their work and treat each new project with responsibility and diligence.<br> We believe that the environment in which human beings live should be not only functional, but also aimed at positive emotion.<br>

            Every new decision is your fantasies and desires, realized by us.<br><p>
          <br><br>
      </div>
    </div>
    <div style="padding-bottom: 3%;"></div>
    </div>
    <div id="footer" class="container">
      <div class="row row-col-2">
        <div class="col-sm-6"><p>This site is an intellectual property of Sokol Design</p></div>
        <div class="col"><p style="color: black !important;">My social media<a href="https://instagram.com/_sokolenok_1?utm_medium=copy_link"><img id="instagram" src="{% static 'image/instagram.svg' %}"></a></p></div>
      </div>
    </div>

  </div>



</body>
</html>